services:
  - type: web
    name: taskflow-backend
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://nwnbhathiya:taskflow12345@cluster0.hslu0xh.mongodb.net/taskflow?retryWrites=true&w=majority
      - key: PORT
        value: "5000"
